[package]
name = "smb-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smb = { path = "../smb" }
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros", "net"] }
