pipeline:
  build:
    image: git.public.arvinderd.com/bender/custom-rust:latest
    commands:
      - cargo build

  test:
    image: git.public.arvinderd.com/bender/custom-rust:latest
    commands:
      - cargo test

  lint:
    image: git.public.arvinderd.com/bender/custom-rust:latest
    commands:
      - cargo fmt -- --check --files-with-diff
      - cargo clippy --no-deps

  # test with big-endian
  miri:
    image: git.public.arvinderd.com/bender/custom-rust:latest
    commands:
      - cargo +nightly miri test --target mips64-unknown-linux-gnuabi64
